### PR TITLE
add android support

### PR DESCRIPTION
**Pull request by hyp**
### Motivation:

Now that swift has an Android module, we should use it in swift-log to build for android.

### Modifications:

Add `Android` imports where needed. This is specifically for Swift 6+.

### Result:

I can build swift-log for android

### CODE REVIEW

**Comment by hyp** [comment]
CC @FranzBusch

**Comment by hyp** [comment]
@swift-server-bot test this please

**Comment by compnerd** [comment]
@swift-server-bot test this please

**Comment by compnerd** [comment]
@swift-server-bot please test

**Comment by hyp** [comment]
CC @ktoso

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Review by ktoso — APPROVED** [review]
Looks fine to me, thanks Alex!

**Pull request merged**
