### PR TITLE
Add NSHipster/swift-log-github-actions to list of backends

### PR DESCRIPTION
**Pull request by mattt**
Updates the list of `SwiftLog` backend implementations to include [swift-log-github-actions](https://github.com/NSHipster/swift-log-github-actions).

### Motivation:

In the development of [SwiftDoc](https://github.com/SwiftDocOrg/swift-doc) and other libraries, I've made extensive use of [GitHub Actions](https://github.com/features/actions) for CI/CD. When executing Swift code in this context, I wanted an easy way to opt-in to [workflow commands](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions), which, for example, allow errors to be surfaced in GitHub's UI like this:

github-actions-ui

I thought that this functionality might be useful for anyone else developing on GitHub's infrastructure, and wanted to share it here for greater visibility.

### Modifications:

Appended `NSHipster/swift-log-github-actions` to the list of implementations in the README.

### Result:

This PR makes no changes to code, just the README.

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-server-bot  test the please

**Comment by tomerd** [comment]
thanks @mattt could you please rebase on master, for whatever reason GitHub won't let me do that myself

**Comment by mattt** [comment]
@tomerd Done! (I thought clicking the <kbd>Update this branch</kbd> button on GitHub would do the trick, but it used a merge commit instead of rebasing. I rebased locally and force-pushed to my fork, which should resolve things.)

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Pull request merged**
