### PR TITLE
Make SwiftLogNoOpLogHandler.init() public

### PR DESCRIPTION
**Pull request by adam-fowler**
I want to cry

### CODE REVIEW

**Comment by ktoso** [comment]
Oh my that's silly 😢 😂

**Comment by ktoso** [comment]
We can make a 1.3.1 soon, I'd count that as fixup rather than new API after all.

Thanks for the PR @adam-fowler, that was so easy to miss... I didn't think we needed a test for a noop heh but that would have helped spot it I guess -- lesson learnt 🤷‍♂️

**Comment by adam-fowler** [comment]
@ktoso cheers thanks

**Comment by ktoso** [comment]
Heads up notice, we'll cut a 1.3.1 tomorrow - since there's not much reason not to

**Comment by ktoso** [comment]
Meh, let's call it 1.4.0 since technically we're "adding API".

**Comment by ktoso** [comment]
And it's out: https://github.com/apple/swift-log/releases/tag/1.4.0

**Pull request merged**
