### PR TITLE
update recent addition to 5.0 syntax

### PR DESCRIPTION
**Pull request by tomerd**
motivation: support 5.0 clients

changes: return value explicitly

### CODE REVIEW

**Comment by tomerd** [comment]
see https://github.com/swift-server/swift-service-lifecycle/pull/129

**Review by ktoso — COMMENTED** [review]
Lgtm, but there's a discussion to have here. During https://github.com/apple/swift-log/pull/238 the consensus was to drop 5.0 support, so that's what we did and documented in release notes, removed the CI etc. So if we want to retract that move we need to do so properly, rather than with an adhoc fix that will regress again without CI.

The summary is that the 5.0 compiler can't survive parsing a task local, even when #if-ed out. There's no workaround in the language. So we'd have to do an very involved tricky dance to make some test into a separate module, only include it in build in new package files and modify the generate Linux tests script to handle this -- I had done all that but everyone in the review had voted against supporting 5.0 at the cost of this complexity so we dropped it.

So... 5.0 isn't supported, as documented in 1.5 release and adhoc fixing it is not the right way -- either we revive the workarounds I did, or we stick to our decision to drop 5.0

**Comment by tomerd** [comment]
@ktoso right I remember that dicussion. it does means we need to remove the `Package@swift-5.0.swift` file so that SwiftPM will happily satisfy the dependency causing potential issues to downstream projects

**Comment by ktoso** [comment]
Hah I see, we missed to remove the file, here's a PR to rectify that: https://github.com/apple/swift-log/pull/259

**Comment by ktoso** [comment]
Superseded by https://github.com/apple/swift-log/pull/259

**Pull request closed without merging**
