### PR TITLE
add luoxiu/LogDog

### PR DESCRIPTION
**Pull request by luoxiu**
add [luoxiu/LogDog](https://github.com/luoxiu/LogDog)

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Hi there @luoxiu, this looks pretty good, thanks for the PR!

Could you clarify a little bit in your readme how this can be used "through" the swift-log API?
I.e. using the handler with the Logger and perhaps also bootstraping it as a system logging?

The Installation section seems somewhat off, one would expect the dependency to logdog there, not to swift-log, can you clean that up please?

**Comment by luoxiu** [comment]
@ktoso Done! 

Apologize for my carelessness, : |

**Review by ktoso — APPROVED** [review]
Looks good, thanks for fixing the dependency :) 

It would be nice if you noted somewhere in the readme the swift-log compatibility, we can merge the link already though -- thanks!

**Pull request merged**
