### PR TITLE
Logging: port to Windows

### PR DESCRIPTION
**Pull request by compnerd**
This adjusts the APIs to enable building swift-log on Windows.

_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-server-bot add to whitelist

**Comment by compnerd** [comment]
*sigh* its all formatting issues, I'll update this momentarily

**Comment by compnerd** [comment]
With the additional change to add CMake, Im happy to add this to the nightlies on Azure

**Comment by ktoso** [comment]
@weissi No milestone assigned when merged?

Added 1.3.0.

**Comment by weissi** [comment]
@compnerd please let us know when you'd need us to cut a release to ship this.

**Pull request merged**
