### PR TITLE
Codable Logger.Level

### PR DESCRIPTION
**Pull request by JulianKahnert**
Add codable to `Logger.Level` for simple Encoding and Decoding.

### Motivation:

Logs may be sent to as json to a REST endpoint. To create a simple serialization, Logger.Level could implement Codable.

### Modifications:

Made Logger.Level adopt `Codable`.

### Result:

Easy encoding and decoding of e.g. a struct that has a `Logger.Level` property.

### CODE REVIEW

**Comment by weissi** [comment]
@swift-server-bot test this please

**Comment by weissi** [comment]
I'm happy with this!

**Comment by ianpartridge** [comment]
+1

**Comment by ktoso** [comment]
LGTM, was iffy about the : String part but that’s fine since ordering we have expressed thanks to the internal ‘ naturalIntegralValue’ — seems fine then. :-)

**Comment by ktoso** [comment]
Was thinking yet a bit more what if we want to send those around in a binary format... but then I could write my own codable for the outer type and handle the enum whichever way I want... so it’s all fine I think. Thanks!

**Comment by JulianKahnert** [comment]
Hi  @weissi @ianpartridge @ktoso , thanks for all your super fast feedback! 🙂 ... so can we merge it?

**Comment by JulianKahnert** [comment]
Hi @weissi, is it possible to create a new release with this PR included? I want to use this changes, but this is [currently not possible](https://forums.swift.org/t/spm-dependency-resolution-version-vs-tag-branch/30089).

**Comment by weissi** [comment]
@JulianKahnert sorry about that, 1.2.0 is released now.

**Pull request merged**
