### PR TITLE
add kiliankoe/swift-log-matrix to list of backends

### PR DESCRIPTION
**Pull request by kiliankoe**
### Motivation:

I just created [swift-log-matrix](https://github.com/kiliankoe/swift-log-matrix) for my personal needs, would be cool to have it in the list here as well :)

### Modifications:

Add a link to the package to list of backends in the README.

### CODE REVIEW

**Comment by kiliankoe** [comment]
Oh whoops, I just realized I copypasted the wrong link. Is a link to GitHub preferable or is the package index even cooler (since it shows supported platforms and Swift versions better)?

**Comment by ktoso** [comment]
Either is okey, sorry I missed this :)

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Review by ktoso — APPROVED** [review]

**Comment by kiliankoe** [comment]
Thanks for the merge @ktoso! 😊

**Pull request merged**
